"use client";

import { useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { ArrowLeft, ArrowRight, CheckCircle2, Gem, RefreshCw, X } from "lucide-react";
import { useLocale } from "next-intl";
import { useSearchParams } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { ErrorState } from "@/components/ui/error-state";
import { InfoTooltip } from "@/components/ui/info-tooltip";
import { LoadingState } from "@/components/ui/loading-state";
import { PageHeader } from "@/components/ui/page-header";
import { Link } from "@/i18n/navigation";
import { useBranchContext } from "@/contexts/branch-context";
import { usePermissions } from "@/hooks/use-permissions";
import { apiClient, generateUUID } from "@/lib/api/client";
import { buildSharedTaxRequest, SharedReceiveSection, type SharedReceiveState } from "@/components/inventory/shared-receive-section";

type RecordLike = Record<string, any>;
const initialReceive: SharedReceiveState = { supplierId: "", locationId: "", purchaseDate: new Date().toISOString().slice(0, 10), taxTreatment: "", notes: "", rcmEvidence: {} };
const initialForm: RecordLike = { description: "", stoneName: "", stoneType: "", shape: "", color: "", tone: "", toneLevel: "", saturation: "", opticalEffect: "", origin: "", certificateAuthority: "", certificateNumber: "", otherDescription: "", carat: "", purchaseCost: "", additionalCost: "", currentStoneValue: "", sellingPrice: "", markupPercent: "", maximumDiscountPercent: "", notes: "", rfid: "" };
function Section({ number, title, children }: { number: number; title: string; children: ReactNode }) { return <Card className="space-y-4 p-5"><h2 className="flex items-center gap-2 text-sm font-black"><span className="grid h-7 w-7 place-items-center rounded-full bg-brand-600 text-[11px] text-white">{number}</span>{title}</h2>{children}</Card>; }
function Field({ label, value, onChange, type = "text", required = false, readOnly = false, info }: { label: string; value: any; onChange?: (value: string) => void; type?: string; required?: boolean; readOnly?: boolean; info?: { label: string; text: string } }) { return <label className="space-y-1"><span className="flex items-center gap-1 text-[11px] font-bold text-slate-500">{label}{required ? " *" : ""}{info && <InfoTooltip {...info} />}</span><input aria-label={`${label}${required ? " *" : ""}`} className={`input-base w-full ${readOnly ? "bg-slate-100 dark:bg-navy-950" : ""}`} type={type} step="any" value={value ?? ""} required={required} readOnly={readOnly} onChange={(event) => onChange?.(event.target.value)} /></label>; }
function SelectField({ label, value, onChange, options, required = false }: { label: string; value: any; onChange: (value: string) => void; options: Array<RecordLike>; required?: boolean }) { return <label className="space-y-1"><span className="block text-[11px] font-bold text-slate-500">{label}{required ? " *" : ""}</span><select aria-label={`${label}${required ? " *" : ""}`} className="input-base w-full" value={value ?? ""} required={required} onChange={(event) => onChange(event.target.value)}><option value="">—</option>{options.map((option) => <option key={option.id || option.value} value={option.id || option.value}>{option.label}</option>)}</select></label>; }
const money = (value: any, locale: string) => value === null || value === undefined || value === "" ? "—" : new Intl.NumberFormat(locale === "ar" ? "ar-AE" : "en-AE", { style: "currency", currency: "AED", maximumFractionDigits: 8 }).format(Number(value));

export default function LooseGemStonePage() {
  const locale = useLocale(); const rtl = locale === "ar"; const searchParams = useSearchParams(); const supplierHint = searchParams.get("supplierId") || "";
  const { branchId, isReady } = useBranchContext(); const { hasPermission } = usePermissions();
  const [contract, setContract] = useState<RecordLike | null>(null); const [form, setForm] = useState<RecordLike>(initialForm); const [receive, setReceive] = useState<SharedReceiveState>(initialReceive); const [preview, setPreview] = useState<RecordLike | null>(null); const [sharedPreview, setSharedPreview] = useState<RecordLike | null>(null); const [prepared, setPrepared] = useState<RecordLike | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [previewLoading, setPreviewLoading] = useState(false); const [submitting, setSubmitting] = useState(false); const [confirmationOpen, setConfirmationOpen] = useState(false); const [result, setResult] = useState<RecordLike | null>(null); const [replay, setReplay] = useState<RecordLike | null>(null); const [conflict, setConflict] = useState<RecordLike | null>(null);
  const keyRef = useRef<string | null>(null); const requestRef = useRef<RecordLike | null>(null); const fingerprintRef = useRef<string | null>(null);
  const update = (key: string, value: any) => setForm((current) => ({ ...current, [key]: value })); const updateReceive = (key: keyof SharedReceiveState, value: string) => setReceive((current) => ({ ...current, [key]: value })); const options = (category: string) => (contract?.masterOptions?.[category] || []).filter((row: RecordLike) => row.isActive !== false); const diagnostics = typeof window !== "undefined" && new URLSearchParams(window.location.search).get("acceptanceDiagnostics") === "1";
  const labels = rtl ? { title: "إضافة حجر كريم حر", desc: "إدخال بيانات حجر كريم منفرد واستلامه.", back: "كل المخزون", refresh: "تحديث", ready: "البيانات مكتملة", incomplete: "أكمل البيانات المطلوبة" } : { title: "Add Loose Gem Stone", desc: "Enter and receive one loose gemstone.", back: "All Inventory", refresh: "Refresh", ready: "Receipt data complete", incomplete: "Complete required data" };
  const field = rtl ? { description: "وصف القطعة", stoneName: "اسم الحجر", stoneType: "نوع الحجر", shape: "الشكل", color: "اللون", tone: "النغمة", toneLevel: "مستوى النغمة", saturation: "التشبع", opticalEffect: "التأثير البصري", origin: "المنشأ", certificateAuthority: "جهة الشهادة", certificateNumber: "رقم الشهادة", carat: "وزن الحجر بالقيراط (CT)", purchase: "تكلفة الشراء قبل الضريبة", additional: "تكلفة إضافية", current: "القيمة الحالية للحجر", selling: "سعر البيع", markup: "نسبة الزيادة %", discount: "الخصم الأقصى %", notes: "ملاحظات" } : { description: "Item Description", stoneName: "Stone Name", stoneType: "Stone Type", shape: "Shape", color: "Color", tone: "Tone", toneLevel: "Tone Level", saturation: "Saturation", opticalEffect: "Optical Effect", origin: "Origin", certificateAuthority: "Certificate Authority", certificateNumber: "Certificate Number", carat: "Stone Carat Weight (CT)", purchase: "Purchase Cost Pre-Tax", additional: "Additional Cost", current: "Current Stone Value", selling: "Selling Price", markup: "Markup %", discount: "Maximum Discount %", notes: "Notes" };
  const load = async (quiet = false) => { if (!isReady) return; quiet ? setRefreshing(true) : setLoading(true); setError(""); try { const response = await apiClient<any>("/inventory-v2/loose-gemstone/contract", { locale, branchId: branchId || undefined }); setContract(response?.data || response); } catch (caught: any) { setError(caught?.message || (rtl ? "تعذر تحميل البيانات." : "Could not load profile data.")); } finally { setLoading(false); setRefreshing(false); } };
  useEffect(() => { void load(); }, [branchId, isReady]); useEffect(() => { if (!contract || !supplierHint) return; const supplier = contract.suppliers?.find((entry: RecordLike) => entry.id === supplierHint && String(entry.status || "").toLowerCase() !== "inactive"); if (supplier) setReceive((current) => current.supplierId ? current : { ...current, supplierId: supplier.id }); }, [contract, supplierHint]);
  const selectors: Array<[string, string]> = [["stoneType", "GEMSTONE_TYPE"], ["shape", "GEMSTONE_SHAPE"], ["color", "GEMSTONE_COLOR"], ["tone", "GEMSTONE_TONE"], ["toneLevel", "GEMSTONE_TONE_LEVEL"], ["saturation", "GEMSTONE_SATURATION"], ["opticalEffect", "GEMSTONE_OPTICAL_EFFECT"], ["origin", "GEMSTONE_ORIGIN"]];
  const selectedValueIsOther = (key: string, category: string) => options(category).some((row: RecordLike) => String(row.id || row.value) === String(form[key] || "") && /\bother\b/i.test(String(row.label || "")));
  const needsOtherDescription = selectedValueIsOther("stoneName", "GEMSTONE_NAME") || selectors.some(([key, category]) => selectedValueIsOther(key, category));
  const profileItem = useMemo(() => ({ profile: "LOOSE_GEMSTONE", inventoryProfile: "LOOSE_GEMSTONE", description: form.description, looseDetails: { stoneName: form.stoneName, stoneType: form.stoneType, shape: form.shape, color: form.color, tone: form.tone, toneLevel: form.toneLevel, saturation: form.saturation, opticalEffect: form.opticalEffect, origin: form.origin, certificateAuthority: form.certificateAuthority, certificateNumber: form.certificateNumber, otherDescription: form.otherDescription, carat: form.carat, purchasePrice: form.purchaseCost, additionalCost: form.additionalCost, currentStoneValue: form.currentStoneValue, sellingPrice: form.sellingPrice, markupPercent: form.markupPercent, maximumDiscountPercent: form.maximumDiscountPercent, notes: form.notes }, purchasePricePreTax: form.purchaseCost, additionalCost: form.additionalCost, currentStoneValue: form.currentStoneValue, sellingPrice: form.sellingPrice, markupPercent: form.markupPercent, maximumDiscountPercent: form.maximumDiscountPercent, taxTreatment: receive.taxTreatment, taxContext: receive.rcmEvidence }), [form, receive.rcmEvidence, receive.taxTreatment]);
  const readyForPreview = Boolean(contract && branchId && receive.supplierId && receive.locationId && receive.purchaseDate && receive.taxTreatment && form.description && form.stoneName && form.carat && Number(form.carat) > 0 && form.purchaseCost !== "" && form.currentStoneValue !== "" && form.sellingPrice !== ""); const profileFingerprint = JSON.stringify(profileItem);
  useEffect(() => { setPreview(null); setSharedPreview(null); setPrepared(null); setResult(null); keyRef.current = null; requestRef.current = null; fingerprintRef.current = null; if (!readyForPreview) return; let cancelled = false; const timer = window.setTimeout(async () => { setPreviewLoading(true); setError(""); try { const response = await apiClient<any>("/inventory-v2/loose-gemstone/preview", { method: "POST", locale, branchId: branchId || undefined, body: JSON.stringify({ item: profileItem }) }); if (!cancelled) setPreview(response?.data || response); } catch (caught: any) { if (!cancelled) setError(caught?.message || (rtl ? "تعذر إكمال المعاينة." : "Preview failed.")); } finally { if (!cancelled) setPreviewLoading(false); } }, 250); return () => { cancelled = true; window.clearTimeout(timer); }; }, [branchId, locale, profileFingerprint, profileItem, readyForPreview, rtl]);
  const profileReady = Boolean(preview?.readiness?.profilePreview === "READY" && preview?.readiness?.salePriceAccepted !== false);
  const receiveItem = useMemo(() => { if (!profileReady || !preview) return null; const details = preview.piece; const base = preview.purchase.purchaseBasePreTax; const currentBase = preview.current.currentStoneValuePreTax; const certificate = details.certificateNumber && details.masterData?.certificateAuthority ? { issuerId: details.masterData.certificateAuthority, certificateNumber: details.certificateNumber, issueDate: receive.purchaseDate } : undefined; const piece = { profile: "LOOSE_GEMSTONE", inventoryProfile: "LOOSE_GEMSTONE", type: "gemstone", category: "Loose Gem Stone", name: form.description, description: form.description, unitCost: base, grossWeight: details.derivedWeightGrams, purchaseCost: base, sellingPrice: preview.sale?.finalSalePrice, inventoryCode: "GS", itemCode: "LOS", locationId: receive.locationId, purchaseDate: receive.purchaseDate, rfid: form.rfid || undefined, ...(certificate ? { certificate } : {}), looseDetails: { ...details, masterData: details.masterData }, looseFinancial: { purchasePricePreTax: preview.purchase.purchaseCostPreTax, additionalCost: preview.purchase.additionalCost }, currentValuation: { rateSource: "LOOSE_GEMSTONE_VALUATION", goldRate: null, goldValue: null, makingValue: null, certificateValue: null, componentValue: currentBase, vatRate: preview.current.taxSnapshot.effectiveVatRate, vatRateSource: "TAX_ENGINE", vatBase: currentBase, vatAmount: preview.current.currentVAT, totalValue: preview.current.currentTotalTaxInclusive }, pricing: { sellingPrice: preview.sale?.finalSalePrice, markupPercent: details.markupPercent, maximumDiscountPercent: details.maximumDiscountPercent, minimumSellingPrice: preview.sale?.minimumAllowedSellingPrice, manualPriceAllowed: false } }; return { ...piece, quantity: 1, perPiece: [piece] }; }, [form.description, form.rfid, preview, profileReady, receive.locationId, receive.purchaseDate]);
  const taxSummary = sharedPreview?.tax || sharedPreview?.summary || sharedPreview; const sharedReady = Boolean(sharedPreview && sharedPreview.success !== false && profileReady);
  useEffect(() => { if (!receiveItem || !profileReady) return; let cancelled = false; const timer = window.setTimeout(async () => { try { const response = await apiClient<any>("/inventory-v2/receive-preview", { method: "POST", locale, branchId: branchId || undefined, body: JSON.stringify({ supplierId: receive.supplierId, warehouseId: branchId, branchId, purchaseDate: receive.purchaseDate, locationId: receive.locationId, items: [receiveItem], inventoryV2: true, ...buildSharedTaxRequest(receive, contract?.taxPolicy) }) }); if (!cancelled) setSharedPreview(response?.data || response); } catch (caught: any) { if (!cancelled) { setSharedPreview(null); setError(caught?.message || (rtl ? "تعذر إكمال ملخص الضريبة." : "Shared preview failed.")); } } }, 250); return () => { cancelled = true; window.clearTimeout(timer); }; }, [branchId, contract?.taxPolicy, locale, receive, receiveItem, profileReady, rtl]);
  useEffect(() => { if (!receiveItem || !sharedReady || !preview) return; const idempotencyKey = generateUUID(); const exactRequest = Object.freeze({ supplierId: receive.supplierId, warehouseId: branchId, branchId, purchaseDate: receive.purchaseDate, locationId: receive.locationId, notes: receive.notes || undefined, inventoryV2: true, profile: "LOOSE_GEMSTONE", idempotencyKey, ...buildSharedTaxRequest(receive, contract?.taxPolicy), items: [receiveItem] }); keyRef.current = idempotencyKey; requestRef.current = exactRequest; fingerprintRef.current = JSON.stringify({ profileItem, request: exactRequest }); setPrepared(exactRequest); }, [branchId, contract?.taxPolicy, profileItem, preview, receive, receiveItem, sharedReady]);
  const finalFingerprint = JSON.stringify({ profileItem, request: prepared }); const canReceive = Boolean(hasPermission("suppliers.create") && branchId && profileReady && sharedReady && prepared && !previewLoading && fingerprintRef.current === finalFingerprint);
  const confirmReceive = async () => { if (!canReceive || !requestRef.current || !keyRef.current) return; setSubmitting(true); setError(""); try { const response = await apiClient<any>("/purchase-orders/receive", { method: "POST", locale, branchId: branchId || undefined, idempotencyKey: keyRef.current, body: JSON.stringify(requestRef.current) }); setResult(response?.data || response); setConfirmationOpen(false); } catch (caught: any) { setError(caught?.message || (rtl ? "فشل الاستلام." : "Receive failed.")); } finally { setSubmitting(false); } };
  const replayExact = async () => { if (!requestRef.current || !keyRef.current) return; try { const response = await apiClient<any>("/purchase-orders/receive", { method: "POST", locale, branchId: branchId || undefined, idempotencyKey: keyRef.current, body: JSON.stringify(requestRef.current) }); setReplay(response?.data || response); } catch (caught: any) { setReplay({ status: caught?.status || null, errorCode: caught?.errorCode || null, message: caught?.message || "Replay failed" }); } };
  const replayChanged = async () => { if (!requestRef.current || !keyRef.current) return; try { await apiClient<any>("/purchase-orders/receive", { method: "POST", locale, branchId: branchId || undefined, idempotencyKey: keyRef.current, body: JSON.stringify({ ...requestRef.current, notes: `${receive.notes || ""} [changed-payload]` }) }); setConflict({ status: "UNEXPECTED_SUCCESS" }); } catch (caught: any) { setConflict({ status: caught?.status || null, errorCode: caught?.errorCode || null, message: caught?.message || "Conflict response" }); } };
  const reset = () => { setPreview(null); setSharedPreview(null); setPrepared(null); setResult(null); setReplay(null); setConflict(null); keyRef.current = null; requestRef.current = null; fingerprintRef.current = null; }; const BackIcon = rtl ? ArrowRight : ArrowLeft;
  if (loading) return <LoadingState variant="skeleton" />; if (error && !contract) return <ErrorState onRetry={() => void load(true)} />;
  return <div dir={rtl ? "rtl" : "ltr"} className="space-y-6 text-xs"><div className="flex flex-wrap items-start justify-between gap-3"><div><Link href="/inventory" className="mb-3 inline-flex items-center gap-1 font-bold text-slate-400"><BackIcon className="h-4 w-4" />{labels.back}</Link><PageHeader title={labels.title} description={labels.desc} /></div><Button variant="secondary" onClick={() => void load(true)} disabled={refreshing}><RefreshCw className="h-4 w-4" />{labels.refresh}</Button></div>
    <Section number={1} title={rtl ? "التعريف" : "Identification"}><div className="grid gap-3 md:grid-cols-3"><Field label={field.description} value={form.description} onChange={(v) => update("description", v)} required /><SelectField label={field.stoneName} value={form.stoneName} onChange={(v) => update("stoneName", v)} options={options("GEMSTONE_NAME")} required /></div><SharedReceiveSection state={receive} suppliers={contract?.suppliers || []} locations={contract?.locations || []} taxPolicy={contract?.taxPolicy} taxSummary={taxSummary} onChange={updateReceive} rcmVerified={receive.taxTreatment !== "REVERSE_CHARGE" || Object.values(receive.rcmEvidence).every(Boolean)} onRcmVerified={() => undefined} onRcmEvidenceChange={(evidence) => setReceive((current) => ({ ...current, rcmEvidence: evidence }))} /></Section>
    <Section number={2} title={rtl ? "بيانات الحجر" : "Gem Stone"}><div className="grid gap-3 md:grid-cols-3">{selectors.map(([key, category]) => <SelectField key={key} label={field[key as keyof typeof field] as string} value={form[key]} onChange={(v) => update(key, v)} options={options(category)} />)}</div><div className="mt-3 grid gap-3 md:grid-cols-3"><SelectField label={field.certificateAuthority} value={form.certificateAuthority} onChange={(v) => update("certificateAuthority", v)} options={options("CERTIFICATE_AUTHORITY")} /><Field label={field.certificateNumber} value={form.certificateNumber} onChange={(v) => update("certificateNumber", v)} /><Field label={rtl ? "وصف قيمة أخرى" : "Other value description"} value={form.otherDescription} onChange={(v) => update("otherDescription", v)} required={needsOtherDescription} /><Field label={field.notes} value={form.notes} onChange={(v) => update("notes", v)} /></div></Section>
    <Section number={3} title={rtl ? "الشراء" : "Purchase"}><div className="grid gap-3 md:grid-cols-4"><Field label={field.carat} value={form.carat} onChange={(v) => update("carat", v)} type="number" required info={{ label: rtl ? "مساعدة الوزن" : "Weight help", text: rtl ? "يُسجّل وزن الحجر بالقيراط، ويُشتق الجرام للتقارير فقط." : "Record the stone in carats; grams are derived for reporting only." }} /><Field label={rtl ? "الوزن المشتق (g)" : "Derived Weight (g)"} value={preview?.piece?.derivedWeightGrams} readOnly /><Field label={field.purchase} value={form.purchaseCost} onChange={(v) => update("purchaseCost", v)} type="number" required info={{ label: rtl ? "مساعدة تكلفة الشراء" : "Purchase cost help", text: rtl ? "أدخل تكلفة الشراء قبل الضريبة." : "Enter the purchase cost before tax." }} /><Field label={field.additional} value={form.additionalCost} onChange={(v) => update("additionalCost", v)} type="number" /></div><div className="mt-3 grid gap-3 md:grid-cols-3"><Field label={rtl ? "ضريبة الشراء" : "Purchase VAT"} value={money(preview?.purchase?.purchaseVAT, locale)} readOnly /><Field label={rtl ? "إجمالي الشراء" : "Purchase Total"} value={money(preview?.purchase?.purchaseTotalTaxInclusive, locale)} readOnly /><Field label={rtl ? "نسبة الضريبة" : "VAT Rate"} value={preview?.purchase?.vatRate ? `${preview.purchase.vatRate}%` : "—"} readOnly /></div></Section>
    <Section number={4} title={rtl ? "القيمة الحالية" : "Current Cost"}><div className="grid gap-3 md:grid-cols-3"><Field label={field.current} value={form.currentStoneValue} onChange={(v) => update("currentStoneValue", v)} type="number" required info={{ label: rtl ? "مساعدة القيمة الحالية" : "Current value help", text: rtl ? "القيمة الحالية مستقلة عن تكلفة الشراء التاريخية." : "Current value is independent from historical purchase cost." }} /><Field label={rtl ? "ضريبة القيمة الحالية" : "Current VAT"} value={money(preview?.current?.currentVAT, locale)} readOnly /><Field label={rtl ? "إجمالي القيمة الحالية" : "Current Total"} value={money(preview?.current?.currentTotalTaxInclusive, locale)} readOnly /></div></Section>
    <Section number={5} title={rtl ? "المبيعات" : "Sales"}><div className="grid gap-3 md:grid-cols-3"><Field label={field.selling} value={form.sellingPrice} onChange={(v) => update("sellingPrice", v)} type="number" required /><Field label={field.markup} value={form.markupPercent} onChange={(v) => update("markupPercent", v)} type="number" /><Field label={field.discount} value={form.maximumDiscountPercent} onChange={(v) => update("maximumDiscountPercent", v)} type="number" /></div></Section>
    <Section number={6} title={rtl ? "الوسم" : "Tag"}><div className="grid gap-3 md:grid-cols-3"><Field label="Barcode" value="GS/LOS/00 — يُنشأ بعد الاستلام" readOnly info={{ label: rtl ? "مساعدة الباركود" : "Barcode help", text: rtl ? "يتم إنشاء الباركود تلقائيًا بعد إتمام الاستلام." : "The barcode is generated automatically after receiving." }} /><Field label="RFID" value={form.rfid || ""} onChange={(v) => update("rfid", v)} /><Field label={rtl ? "الحالة الأولية" : "Initial Status"} value={rtl ? "متاح" : "Available"} readOnly /></div></Section>
    <Section number={7} title={rtl ? "الحالة" : "Status"}><p className="text-slate-600">{rtl ? "كل حجر كريم حر يُسجّل كقطعة مستقلة بأصل وباركود خاصين به." : "Each loose gemstone is recorded as one independent physical Asset with its own barcode."}</p></Section><Section number={8} title={rtl ? "التدقيق والنظام" : "Audit / System"}><p className="text-slate-600">{rtl ? "يتم حفظ المورد والفرع والموقع والتاريخ وسجل الاستلام ضمن العملية." : "Supplier, branch, location, date, and receive history are retained with the transaction."}</p></Section>
    <Card className="space-y-3 border-slate-200 bg-slate-50/80 p-4"><div className="flex flex-wrap items-center gap-3"><Badge tone={profileReady && sharedReady ? "green" : "amber"}>{profileReady && sharedReady ? labels.ready : labels.incomplete}</Badge><Badge tone={hasPermission("suppliers.create") ? "green" : "rose"}>{hasPermission("suppliers.create") ? (rtl ? "صلاحية الاستلام متاحة" : "Receive permission available") : (rtl ? "لا توجد صلاحية الاستلام" : "Receive permission unavailable")}</Badge></div>{error && <p className="text-rose-700">{error}</p>}{diagnostics && prepared && <details data-testid="prepared-receive-payload" className="rounded-xl border border-border bg-background p-3"><summary className="cursor-pointer font-bold">{rtl ? "تفاصيل إثبات الاستلام" : "Receive evidence details"}</summary><pre className="mt-2 max-h-64 overflow-auto whitespace-pre-wrap break-all text-[9px]">{JSON.stringify(prepared, null, 2)}</pre></details>}</Card>
    {result && <Card className="space-y-3 border-emerald-300 bg-emerald-50 p-4 text-emerald-900"><CheckCircle2 className="me-2 inline h-4 w-4" />{rtl ? "تم استلام الحجر الكريم بنجاح." : "Loose Gem Stone received successfully."}{diagnostics && <div className="flex flex-wrap gap-2 pt-2"><Button variant="secondary" onClick={() => void replayExact()}>Replay</Button><Button variant="secondary" onClick={() => void replayChanged()}>Changed payload</Button></div>}{diagnostics && replay && <pre className="whitespace-pre-wrap text-[10px]">{JSON.stringify(replay, null, 2)}</pre>}{diagnostics && conflict && <pre className="whitespace-pre-wrap text-[10px]">{JSON.stringify(conflict, null, 2)}</pre>}</Card>}
    <div className="flex justify-end gap-3"><Button variant="secondary" onClick={reset}><X className="h-4 w-4" />{rtl ? "إلغاء المعاينة" : "Cancel Preview"}</Button><Button onClick={() => setConfirmationOpen(true)} disabled={!canReceive} data-final-receive="true"><Gem className="h-4 w-4" />{rtl ? "استلام المخزون" : "Receive Inventory"}</Button></div>
    {confirmationOpen && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><Card className="max-h-[calc(100vh-2rem)] w-full max-w-2xl space-y-5 overflow-y-auto p-6 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-base font-black">{rtl ? "تأكيد استلام حجر كريم حر" : "Confirm Loose Gem Stone Receive"}</h2><button type="button" aria-label={rtl ? "إغلاق" : "Close"} onClick={() => setConfirmationOpen(false)}><X className="h-5 w-5" /></button></div><div className="grid gap-3 sm:grid-cols-2"><Field label={field.description} value={form.description} readOnly /><Field label={field.carat} value={`${form.carat} CT`} readOnly /><Field label={field.purchase} value={money(preview?.purchase?.purchaseBasePreTax, locale)} readOnly /><Field label={rtl ? "الضريبة" : "VAT"} value={money(preview?.purchase?.purchaseVAT, locale)} readOnly /><Field label={rtl ? "الإجمالي" : "Total"} value={money(preview?.purchase?.purchaseTotalTaxInclusive, locale)} readOnly /><Field label={field.current} value={money(preview?.current?.currentStoneValuePreTax, locale)} readOnly /></div>{diagnostics && <details data-testid="prepared-receive-payload" open className="rounded-xl border border-border bg-slate-50 p-3"><summary className="font-bold">{rtl ? "بيانات العملية" : "Prepared receive request"}</summary><pre className="mt-2 max-h-64 overflow-auto whitespace-pre-wrap break-all text-[9px]">{JSON.stringify(requestRef.current, null, 2)}</pre></details>}<div className="flex justify-end gap-3"><Button variant="secondary" onClick={() => setConfirmationOpen(false)} disabled={submitting}>{rtl ? "إلغاء" : "Cancel"}</Button><Button onClick={() => void confirmReceive()} disabled={submitting}>{submitting ? (rtl ? "جارٍ التنفيذ…" : "Processing…") : (rtl ? "تأكيد الاستلام" : "Confirm Receive")}</Button></div></Card></div>}
  </div>;
}
