const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

const root = path.resolve(__dirname, "..");
const read = (relativePath) => fs.readFileSync(path.join(root, relativePath), "utf8");

const supplierPage = read("app/[locale]/(dashboard)/suppliers/page.tsx");
const supplierDetailsPage = read("app/[locale]/(dashboard)/suppliers/[id]/page.tsx");
const legacyReceivePage = read("app/[locale]/(dashboard)/suppliers/purchases/page.tsx");
const supplierModel = read("backend/src/models/supplier.model.js");
const controller = read("backend/src/controllers/erp.controller.js");
const routes = read("backend/src/routes/erp.routes.js");
const permissionCatalog = read("lib/permissions/catalog.ts");

test("Supplier Master exposes model-supported identity and commercial fields", () => {
  for (const field of ["taxNumber", "commercialRegister", "paymentTerms"]) {
    assert.match(supplierModel, new RegExp(`\\b${field}\\b`));
    assert.match(supplierPage, new RegExp(`form\\.${field}`));
    assert.match(supplierPage, new RegExp(`${field}: form\\.${field}\\.trim\\(\\)`));
  }
  assert.match(supplierPage, /due is maintained by the system/);
});

test("Supplier Master CRUD is company-scoped and supplier IDs are server-generated by default", () => {
  assert.match(controller, /companyId: req\.companyId/);
  assert.match(controller, /GENERATED_ID_FORMATS = \{[\s\S]*Supplier: \{ prefix: "SUP", width: 3 \}/);
  assert.match(controller, /if \(shouldGenerateStringId\)\s*\{?\s*payload\.id = await generateScopedSequentialId/);
  assert.match(routes, /setupCrud\("suppliers", models\.Supplier/);
});

test("Supplier lifecycle and linked-record deletion guard are server-authoritative", () => {
  assert.match(routes, /router\.post\("\/suppliers\/:id\/deactivate"[\s\S]*where: \{ id: req\.params\.id, companyId: req\.companyId \}/);
  assert.match(routes, /router\.post\("\/suppliers\/:id\/reactivate"[\s\S]*where: \{ id: req\.params\.id, companyId: req\.companyId \}/);
  assert.match(routes, /SUPPLIER_HAS_LINKED_RECORDS/);
  assert.match(routes, /supplierId: supplier\.id, companyId: req\.companyId/);
});

test("Supplier lifecycle permissions remain explicitly catalogued and enforced", () => {
  for (const permission of [
    "suppliers.view", "suppliers.create", "suppliers.update", "suppliers.delete",
    "suppliers.deactivate", "suppliers.reactivate",
  ]) {
    assert.match(permissionCatalog, new RegExp(`\\"${permission}\\"`));
    assert.match(routes, new RegExp(permission.replace(".", "\\.")));
  }
});

test("Supplier details exposes read-only history and account statement while payment remains separate", () => {
  assert.match(supplierDetailsPage, /activeTab === "purchases"/);
  assert.match(supplierDetailsPage, /statement/);
  assert.match(supplierDetailsPage, /paymentTerms/);
  assert.match(supplierDetailsPage, /taxNumber/);
  assert.match(supplierDetailsPage, /commercialRegister/);
});

test("Legacy Supplier receive URL redirects to the single canonical Inventory workflow", () => {
  assert.match(legacyReceivePage, /redirect\(`\/\$\{locale\}\/inventory`\)/);
  assert.doesNotMatch(supplierPage, /receiveSupplier|createReceive|purchase-orders\/receive/);
});
