"use client";

import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, ChevronDown, Plus, Trash2, X } from "lucide-react";
import { useLocale } from "next-intl";
import { useSearchParams } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { ErrorState } from "@/components/ui/error-state";
import { LoadingState } from "@/components/ui/loading-state";
import { PageHeader } from "@/components/ui/page-header";
import { useBranchContext } from "@/contexts/branch-context";
import { apiClient, generateUUID } from "@/lib/api/client";
import { buildSharedTaxRequest, SharedReceiveSection, type SharedReceiveState } from "@/components/inventory/shared-receive-section";

type AnyRecord = Record<string, any>;
type Stone = AnyRecord & { id: string; settings: string[] };
const initialReceive: SharedReceiveState = { supplierId: "", locationId: "", purchaseDate: new Date().toISOString().slice(0, 10), taxTreatment: "", notes: "", rcmEvidence: {} };
const initialStone = (id: string): Stone => ({ id, stoneName: "", stoneCaratWeight: "", stoneType: "", shape: "", color: "", tone: "", toneLevel: "", saturation: "", opticalEffect: "", origin: "", position: "", settings: [], treatment: "", stoneCost: "", currentValue: "", notes: "" });
const n = (value: unknown) => Number(value || 0);
const money = (value: unknown, locale: string) => value == null ? "—" : new Intl.NumberFormat(locale === "ar" ? "ar-AE" : "en-AE", { style: "currency", currency: "AED", maximumFractionDigits: 8 }).format(Number(value));

function Field({ label, value, onChange, type = "text", required = false, readOnly = false }: { label: string; value: any; onChange?: (value: string) => void; type?: string; required?: boolean; readOnly?: boolean }) {
  return <label className="space-y-1"><span className="block text-[11px] font-bold text-slate-500">{label}{required ? " *" : ""}</span><input className={`input-base w-full ${readOnly ? "bg-slate-100 dark:bg-navy-950" : ""}`} dir={type === "number" ? "ltr" : undefined} type={type} step="any" value={value ?? ""} required={required} readOnly={readOnly} onChange={(event) => onChange?.(event.target.value)} /></label>;
}
function SelectField({ label, value, onChange, options, required = false, multiple = false }: { label: string; value: any; onChange: (value: any) => void; options: string[]; required?: boolean; multiple?: boolean }) {
  if (multiple) {
    const selected = Array.isArray(value) ? value : [];
    return <div className="space-y-1" dir="auto"><span className="block text-[11px] font-bold text-slate-500">{label}{required ? " *" : ""}</span><details className="group relative"><summary className="input-base flex min-h-[42px] cursor-pointer list-none items-center justify-between gap-2 text-start [&::-webkit-details-marker]:hidden"><span className="truncate text-sm text-slate-600 dark:text-slate-300">{selected.length ? `${selected.length} selected` : "—"}</span><ChevronDown className="h-4 w-4 shrink-0 transition-transform group-open:rotate-180" aria-hidden="true" /></summary><div role="listbox" aria-label={label} aria-multiselectable="true" className="absolute inset-x-0 z-30 mt-1 max-h-60 overflow-y-auto rounded-xl border border-border bg-white p-2 shadow-xl dark:bg-navy-900">{options.map((option) => <label key={option} className="flex cursor-pointer items-center gap-2 rounded-lg px-2 py-2 text-sm hover:bg-slate-100 dark:hover:bg-navy-800"><input type="checkbox" checked={selected.includes(option)} onChange={(event) => onChange(event.target.checked ? [...selected, option] : selected.filter((item: string) => item !== option))} className="h-4 w-4 accent-brand-600" /><span>{option}</span></label>)}</div></details>{selected.length > 0 && <div className="flex min-h-7 flex-wrap gap-1.5 pt-1" aria-label={`${label} selected values`}>{selected.map((option: string) => <span key={option} className="inline-flex items-center gap-1 rounded-full bg-brand-50 px-2 py-1 text-xs font-bold text-brand-800 dark:bg-brand-950/40 dark:text-brand-200"><span>{option}</span><button type="button" className="rounded-full p-0.5 hover:bg-brand-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 dark:hover:bg-brand-900" aria-label={`Remove ${option}`} onClick={() => onChange(selected.filter((item: string) => item !== option))}><X className="h-3 w-3" aria-hidden="true" /></button></span>)}</div>}</div>;
  }
  return <label className="space-y-1"><span className="block text-[11px] font-bold text-slate-500">{label}{required ? " *" : ""}</span><select className="input-base w-full" value={value ?? ""} required={required} onChange={(event) => onChange(event.target.value)}><option value="">—</option>{options.map((option) => <option key={option} value={option}>{option}</option>)}</select></label>;
}
function Section({ number, title, children }: { number: number; title: string; children: React.ReactNode }) { return <Card className="space-y-4 p-5"><h2 className="flex items-center gap-2 text-sm font-black"><span className="grid h-7 w-7 place-items-center rounded-full bg-brand-600 text-[11px] text-white">{number}</span>{title}</h2>{children}</Card>; }

export default function GemStoneJewelleryPage() {
  const locale = useLocale(); const rtl = locale === "ar"; const searchParams = useSearchParams(); const supplierHint = searchParams.get("supplierId") || ""; const { branchId, isReady } = useBranchContext();
  const [contract, setContract] = useState<AnyRecord | null>(null); const [receive, setReceive] = useState(initialReceive); const [draft, setDraft] = useState<AnyRecord>({ description: "", itemCode: "", karat: "21", goldColor: "", brand: "", model: "", modelNumber: "", grossWeight: "", totalGemStoneWeightCt: "", netGoldWeightOverride: "", goldPurchasePrice: "", makingPerGram: "", currentMakingPerGram: "", currentGemStoneValue: "", sellingPrice: "", maximumDiscountPercent: "", rfid: "" });
  const [stones, setStones] = useState<Stone[]>([initialStone("1")]); const [preview, setPreview] = useState<AnyRecord | null>(null); const [sharedPreview, setSharedPreview] = useState<AnyRecord | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [confirmation, setConfirmation] = useState(false); const [result, setResult] = useState<any>(null); const [preparedReceive, setPreparedReceive] = useState<AnyRecord | null>(null); const [rcmVerified, setRcmVerified] = useState(false);
  const update = (key: string, value: any) => setDraft((current: AnyRecord) => ({ ...current, [key]: value })); const updateReceive = (key: keyof SharedReceiveState, value: string) => setReceive((current) => ({ ...current, [key]: value })); const updateStone = (id: string, key: string, value: any) => setStones((current) => current.map((stone) => stone.id === id ? { ...stone, [key]: value } : stone));
  const masters = contract?.masters || []; const options = (category: string): string[] => Array.from(new Set<string>(masters.filter((row: AnyRecord) => row.category === category && row.isActive !== false).map((row: AnyRecord) => String(row.label))));
  const selectedDescription = contract?.itemDescriptions?.find((entry: AnyRecord) => entry.value === draft.description); const item = useMemo(() => ({ profile: "GEMSTONE_JEWELLERY", inventoryProfile: "GEMSTONE_JEWELLERY", ...draft, itemCode: selectedDescription?.itemCode || draft.itemCode, components: stones.map(({ id, ...stone }) => ({ ...stone, componentCarat: stone.stoneCaratWeight, componentType: stone.stoneType })), taxTreatment: receive.taxTreatment, taxContext: receive.rcmEvidence }), [draft, receive, selectedDescription, stones]);
  const profileReady = Boolean(contract && draft.description && selectedDescription && n(draft.grossWeight) > 0 && n(draft.totalGemStoneWeightCt) >= 0 && n(draft.karat) > 0 && n(draft.goldPurchasePrice) > 0 && draft.makingPerGram !== "" && draft.currentMakingPerGram !== "" && draft.currentGemStoneValue !== "" && draft.sellingPrice !== "" && receive.taxTreatment && receive.supplierId && receive.locationId && stones.length && stones.every((stone) => stone.stoneName && n(stone.stoneCaratWeight) > 0 && stone.stoneCost !== ""));
  const receiveBody = useMemo(() => { const base = preview?.historicalPurchase?.purchaseBasePreTax; const piece = { ...item, type: "gemstone", category: "Gem Stone Jewellery", grossWeight: n(draft.grossWeight), purchaseCost: Number(base || 0), unitCost: Number(base || 0), price: Number(draft.sellingPrice), locationId: receive.locationId, sellingPrice: Number(draft.sellingPrice) }; return { ...buildSharedTaxRequest(receive, contract?.taxPolicy), inventoryV2: true, supplierId: receive.supplierId, branchId, purchaseDate: receive.purchaseDate, items: [{ name: draft.description, description: draft.description, quantity: 1, unitCost: Number(base || 0), price: Number(draft.sellingPrice), grossWeight: n(draft.grossWeight), inventoryV2: true, perPiece: [piece] }] }; }, [branchId, contract, draft, item, preview, receive]);
  useEffect(() => { if (!isReady) return; void (async () => { try { const response = await apiClient<any>("/inventory-v2/gem-stone/contract", { locale, branchId: branchId || undefined }); const next = response?.data || response; setContract(next); if (supplierHint && next.suppliers?.some((row: AnyRecord) => row.id === supplierHint)) setReceive((current) => ({ ...current, supplierId: supplierHint })); } catch (caught: any) { setError(caught?.message || "Contract unavailable"); } finally { setLoading(false); } })(); }, [branchId, isReady, locale, supplierHint]);
  useEffect(() => { if (!profileReady) { setPreview(null); setSharedPreview(null); return; } const timer = window.setTimeout(() => void (async () => { try { setError(""); const response = await apiClient<any>("/inventory-v2/gem-stone/preview", { method: "POST", locale, branchId: branchId || undefined, body: JSON.stringify({ item }) }); setPreview(response?.data || response); } catch (caught: any) { setPreview(null); setError(caught?.message || "Profile preview unavailable"); } })(), 250); return () => window.clearTimeout(timer); }, [branchId, item, locale, profileReady]);
  useEffect(() => { if (!preview || !receive.supplierId || !receive.locationId || !receive.taxTreatment) { setSharedPreview(null); return; } const timer = window.setTimeout(() => void (async () => { try { const response = await apiClient<any>("/inventory-v2/receive-preview", { method: "POST", locale, branchId: branchId || undefined, body: JSON.stringify(receiveBody) }); setSharedPreview(response?.data || response); } catch (caught: any) { setSharedPreview(null); setError(caught?.message || "Shared receive preview unavailable"); } })(), 250); return () => window.clearTimeout(timer); }, [branchId, locale, preview, receiveBody]);
  const taxSummary = sharedPreview || preview?.historicalPurchase; const canReceive = Boolean(profileReady && preview?.sale?.priceAccepted && sharedPreview && receive.supplierId && receive.locationId && receive.taxTreatment && (!receive.taxTreatment.includes("REVERSE") || rcmVerified));
  const openConfirmation = () => { if (!canReceive) return; const idempotencyKey = generateUUID(); setPreparedReceive(JSON.parse(JSON.stringify({ ...receiveBody, idempotencyKey }))); setConfirmation(true); };
  const submit = async () => { if (!canReceive || busy || !preparedReceive?.idempotencyKey) return; setBusy(true); setError(""); try { const exactRequest = preparedReceive; const response = await apiClient<any>("/purchase-orders/receive", { method: "POST", locale, branchId: branchId || undefined, headers: { "Idempotency-Key": String(exactRequest.idempotencyKey) }, body: JSON.stringify(exactRequest) }); setResult(response?.data || response); setConfirmation(false); } catch (caught: any) { setError(caught?.message || "Receive failed"); } finally { setBusy(false); } };
  if (loading) return <LoadingState variant="skeleton" />; if (error && !contract) return <ErrorState message={error} onRetry={() => window.location.reload()} />;
  return <div className="space-y-6"><PageHeader title={rtl ? "مجوهرات الأحجار الكريمة" : "Gem Stone Jewellery"} description={rtl ? "تسجيل قطعة مجوهرات واحدة مع أحجار كريمة ومصدر بيانات معتمد." : "Record one jewellery piece with gemstones and approved master data."} /><SharedReceiveSection state={receive} suppliers={contract?.suppliers || []} locations={contract?.locations || []} taxPolicy={contract?.taxPolicy} taxSummary={taxSummary} onChange={updateReceive} onRcmVerified={setRcmVerified} onRcmEvidenceChange={(evidence) => setReceive((current) => ({ ...current, rcmEvidence: evidence }))} rcmVerified={rcmVerified} />
    <Section number={1} title={rtl ? "التعريف" : "Identification"}><div className="grid gap-3 md:grid-cols-3"><SelectField label={rtl ? "وصف القطعة" : "Item Description"} value={draft.description} onChange={(value) => update("description", value)} options={(contract?.itemDescriptions || []).map((entry: AnyRecord) => entry.value)} required /><Field label={rtl ? "العيار" : "Karat"} value={draft.karat} onChange={(value) => update("karat", value)} type="number" required /><Field label={rtl ? "لون الذهب" : "Gold Color"} value={draft.goldColor} onChange={(value) => update("goldColor", value)} /><Field label={rtl ? "العلامة" : "Brand"} value={draft.brand} onChange={(value) => update("brand", value)} /><Field label={rtl ? "الموديل" : "Model"} value={draft.model} onChange={(value) => update("model", value)} /><Field label={rtl ? "كود الصنف" : "Item Code"} value={selectedDescription?.itemCode || ""} readOnly /></div></Section>
    <Section number={2} title={rtl ? "الذهب والوزن" : "Gold and Weight"}><div className="grid gap-3 md:grid-cols-4"><Field label={rtl ? "الوزن الإجمالي (g)" : "Gross Weight (g)"} value={draft.grossWeight} onChange={(value) => update("grossWeight", value)} type="number" required /><Field label={rtl ? "إجمالي الأحجار (CT)" : "Total Gem Stone Weight (CT)"} value={draft.totalGemStoneWeightCt} onChange={(value) => update("totalGemStoneWeightCt", value)} type="number" required /><Field label={rtl ? "تجاوز صافي الذهب" : "Net Gold Override"} value={draft.netGoldWeightOverride} onChange={(value) => update("netGoldWeightOverride", value)} type="number" /><Field label={rtl ? "التحويل" : "Conversion"} value="1 CT = 0.20 g" readOnly /></div><div className="grid gap-3 md:grid-cols-3"><Field label={rtl ? "صافي الذهب" : "Net Gold Weight"} value={preview?.weights?.netGoldWeight} readOnly /><Field label={rtl ? "الذهب الخالص 999.9" : "Pure Gold 999.9"} value={preview?.weights?.pureGoldWeight9999} readOnly /><Field label={rtl ? "وزن الأحجار (g)" : "Gem Stone Weight (g)"} value={preview?.weights?.stoneWeightGrams} readOnly /></div></Section>
    <Section number={3} title={rtl ? "معلومات الأحجار" : "Gem Stone Information"}><div className="space-y-4">{stones.map((stone, index) => <div key={stone.id} className="rounded-2xl border border-border p-4"><div className="mb-3 flex items-center justify-between"><span className="font-black">{rtl ? `حجر ${index + 1}` : `Stone ${index + 1}`}</span>{stones.length > 1 && <Button variant="ghost" onClick={() => setStones((current) => current.filter((entry) => entry.id !== stone.id))}><Trash2 className="h-4 w-4" />{rtl ? "إزالة" : "Remove"}</Button>}</div><div className="grid gap-3 md:grid-cols-3"><SelectField label={rtl ? "اسم الحجر" : "Stone Name"} value={stone.stoneName} onChange={(value) => updateStone(stone.id, "stoneName", value)} options={options("GEMSTONE_NAME")} required /><Field label={rtl ? "الوزن (CT)" : "Weight (CT)"} value={stone.stoneCaratWeight} onChange={(value) => updateStone(stone.id, "stoneCaratWeight", value)} type="number" required /><SelectField label={rtl ? "النوع" : "Type"} value={stone.stoneType} onChange={(value) => updateStone(stone.id, "stoneType", value)} options={options("GEMSTONE_TYPE")} /><SelectField label={rtl ? "الشكل" : "Shape"} value={stone.shape} onChange={(value) => updateStone(stone.id, "shape", value)} options={options("GEMSTONE_SHAPE")} /><SelectField label={rtl ? "اللون" : "Color"} value={stone.color} onChange={(value) => updateStone(stone.id, "color", value)} options={options("GEMSTONE_COLOR")} /><SelectField label={rtl ? "الموضع" : "Position"} value={stone.position} onChange={(value) => updateStone(stone.id, "position", value)} options={options("GEMSTONE_POSITION")} /><SelectField label={rtl ? "الإعدادات" : "Settings"} value={stone.settings} onChange={(value) => updateStone(stone.id, "settings", value)} options={options("GEMSTONE_SETTING")} multiple /><Field label={rtl ? "تكلفة الحجر" : "Stone Cost"} value={stone.stoneCost} onChange={(value) => updateStone(stone.id, "stoneCost", value)} type="number" required /><Field label={rtl ? "القيمة الحالية" : "Current Value"} value={stone.currentValue} onChange={(value) => updateStone(stone.id, "currentValue", value)} type="number" /></div></div>)}<Button variant="secondary" onClick={() => setStones((current) => [...current, initialStone(String(Date.now()))])}><Plus className="h-4 w-4" />{rtl ? "إضافة حجر" : "Add Stone"}</Button></div></Section>
    <Section number={4} title={rtl ? "الشراء" : "Purchase"}><div className="grid gap-3 md:grid-cols-4"><Field label={rtl ? "سعر الذهب عند الشراء / g" : "Gold Purchase Price / g"} value={draft.goldPurchasePrice} onChange={(value) => update("goldPurchasePrice", value)} type="number" required /><Field label={rtl ? "المصنعية / g" : "Making / g"} value={draft.makingPerGram} onChange={(value) => update("makingPerGram", value)} type="number" required /><Field label={rtl ? "قيمة الذهب" : "Gold Value"} value={money(preview?.historicalPurchase?.goldValue, locale)} readOnly /><Field label={rtl ? "إجمالي الشراء" : "Total Purchase"} value={money(preview?.historicalPurchase?.totalPurchaseCost, locale)} readOnly /></div></Section>
    <Section number={5} title={rtl ? "التكلفة الحالية" : "Current Cost"}><div className="grid gap-3 md:grid-cols-4"><Field label={rtl ? "المصنعية الحالية / g" : "Current Making / g"} value={draft.currentMakingPerGram} onChange={(value) => update("currentMakingPerGram", value)} type="number" required /><Field label={rtl ? "قيمة الأحجار الحالية" : "Current Gem Stone Value"} value={draft.currentGemStoneValue} onChange={(value) => update("currentGemStoneValue", value)} type="number" required /><Field label={rtl ? "قيمة حالية" : "Current Total"} value={money(preview?.currentCost?.totalCurrentCost, locale)} readOnly /><Field label={rtl ? "سعر الذهب الحالي" : "Current Gold Rate"} value={preview?.gold?.currentRate} readOnly /></div></Section>
    <Section number={6} title={rtl ? "البيع" : "Sales"}><div className="grid gap-3 md:grid-cols-4"><Field label={rtl ? "سعر بيع القطعة" : "Piece Selling Price"} value={draft.sellingPrice} onChange={(value) => update("sellingPrice", value)} type="number" required /><Field label={rtl ? "الخصم الأقصى %" : "Maximum Discount %"} value={draft.maximumDiscountPercent} onChange={(value) => update("maximumDiscountPercent", value)} type="number" /><Field label={rtl ? "الحد الأدنى" : "Minimum Allowed"} value={money(preview?.sale?.minimumAllowedPrice, locale)} readOnly /><Field label={rtl ? "الربح المتوقع" : "Expected Profit"} value={money(preview?.sale?.expectedProfit, locale)} readOnly /></div></Section>
    <Section number={7} title={rtl ? "الهوية والوسم" : "Tag and Identity"}><div className="grid gap-3 md:grid-cols-3"><Field label={rtl ? "الباركود" : "Barcode"} value={rtl ? "يُنشأ بعد الاستلام" : "Generated after receive"} readOnly /><Field label="RFID" value={draft.rfid} onChange={(value) => update("rfid", value)} /><Field label={rtl ? "الحالة الأولية" : "Initial Status"} value="AVAILABLE" readOnly /></div></Section>
    <Section number={8} title={rtl ? "الموقع والحالة" : "Location and Status"}><div className="grid gap-3 md:grid-cols-3"><Field label={rtl ? "الفرع" : "Branch"} value={branchId || "—"} readOnly /><Field label={rtl ? "الموقع" : "Location"} value={receive.locationId} readOnly /><Field label={rtl ? "الحالة" : "Status"} value="AVAILABLE" readOnly /></div></Section>
    <Section number={9} title={rtl ? "المراجعة والنظام" : "Audit and System"}><Field label={rtl ? "ملاحظات" : "Notes"} value={receive.notes} onChange={(value) => updateReceive("notes", value)} /></Section>
    <Card className="space-y-3 p-4"><div className="flex flex-wrap gap-2"><Badge tone={profileReady ? "green" : "amber"}>{rtl ? `معاينة الملف: ${profileReady ? "جاهزة" : "غير جاهزة"}` : `Profile Preview: ${profileReady ? "READY" : "NOT READY"}`}</Badge><Badge tone={sharedPreview ? "green" : "amber"}>{rtl ? `المعاينة المشتركة: ${sharedPreview ? "جاهزة" : "غير جاهزة"}` : `Shared Receive Preview: ${sharedPreview ? "READY" : "NOT READY"}`}</Badge></div>{error && <p className="text-sm text-rose-600">{error}</p>}{result && <p className="text-sm font-bold text-emerald-700"><CheckCircle2 className="me-1 inline h-4 w-4" />{rtl ? "تم الاستلام بنجاح" : "Receive completed"}</p>}<div className="flex justify-end"><Button onClick={openConfirmation} disabled={!canReceive}>{rtl ? "مراجعة وتأكيد الاستلام" : "Review and Confirm Receive"}</Button></div></Card>
    {confirmation && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><Card className="w-full max-w-2xl space-y-5 p-6"><h2 className="text-base font-black">{rtl ? "تأكيد استلام مجوهرات الأحجار الكريمة" : "Confirm Gem Stone Jewellery Receive"}</h2><div className="grid gap-3 sm:grid-cols-2"><Field label={rtl ? "المورد" : "Supplier"} value={receive.supplierId} readOnly /><Field label={rtl ? "الموقع" : "Location"} value={receive.locationId} readOnly /><Field label={rtl ? "الشراء قبل الضريبة" : "Purchase Base Before Tax"} value={money(preview?.historicalPurchase?.purchaseBasePreTax, locale)} readOnly /><Field label={rtl ? "الضريبة" : "VAT"} value={money(preview?.historicalPurchase?.vatAmount, locale)} readOnly /></div>{preparedReceive && <details data-testid="prepared-receive-payload" className="rounded border border-slate-200 p-3"><summary className="cursor-pointer text-sm font-bold">{rtl ? "تفاصيل الطلب المحفوظ للمراجعة" : "Prepared request details"}</summary><pre className="mt-3 max-h-72 overflow-auto whitespace-pre-wrap text-xs">{JSON.stringify(preparedReceive, null, 2)}</pre></details>}<div className="flex justify-end gap-3"><Button variant="secondary" onClick={() => setConfirmation(false)} disabled={busy}>{rtl ? "إلغاء" : "Cancel"}</Button><Button onClick={() => void submit()} disabled={busy || !preparedReceive}>{rtl ? "تأكيد الاستلام" : "Confirm Receive"}</Button></div></Card></div>}
  </div>;
}
