/**
 * Phase 32.2-Fix — configuration for the inventory item-type Add/Edit forms.
 *
 * The forms are type-driven: asset.type selects a variant set (inventory_subtype)
 * and a Section-2 field group. Type-specific attributes are stored in
 * Asset.metadata (JSONB) with metadata_schema_version = 1 — no new per-type
 * tables are introduced in this phase.
 *
 * Final stored barcodes are ALWAYS generated by the backend
 * (barcode-identity.service). The form only chooses taxonomy (inventory code /
 * item code / karat) and renders a read-only preview.
 */

import type { AssetType } from "@/lib/types";

export const INVENTORY_METADATA_SCHEMA_VERSION = 1;

// Documented frontend fallback for the owner-approved provisional Watch type,
// used only when the company-scoped barcode settings API is unavailable
// (e.g. local/demo mode). The database rows remain the source of truth.
export const WATCH_FALLBACK_CODES = Object.freeze({
  inventoryCode: "WT",
  itemCode: "WCH",
  karatCode: "00",
});

export interface InventoryVariant {
  /** Stored in Asset.inventory_subtype. */
  value: string;
  label: string;
  labelAr: string;
  /** Loose stones/pearls — backend requires a configured default karat code. */
  loose?: boolean;
  /** 24K / gold bar variant. */
  bar?: boolean;
}

export interface InventoryTypeConfig {
  type: AssetType;
  label: string;
  labelAr: string;
  /** Default inventory code (settings override this when available). */
  defaultInventoryCode: string;
  /** Whether a karat value is normally required for this family. */
  karatRequired: boolean;
  /** Whether a positive weight is required (gold-weight). */
  weightRequired: boolean;
  /** Section-2 heading. */
  section2Title: string;
  section2TitleAr: string;
  variants: InventoryVariant[];
}

export const INVENTORY_TYPE_CONFIGS: InventoryTypeConfig[] = [
  {
    type: "gold-weight",
    label: "Gold By Weight",
    labelAr: "ذهب بالوزن",
    defaultInventoryCode: "GW",
    karatRequired: true,
    weightRequired: true,
    section2Title: "Weight & Gold Details",
    section2TitleAr: "تفاصيل الوزن والذهب",
    variants: [
      { value: "gold-weight-jewellery", label: "Gold By Weight Jewellery", labelAr: "مجوهرات ذهب بالوزن" },
      { value: "gold-weight-bar", label: "Gold By Weight 24K / Gold Bar", labelAr: "ذهب 24 / سبيكة", bar: true },
    ],
  },
  {
    type: "gold-piece",
    label: "Gold By Piece",
    labelAr: "ذهب بالقطعة",
    defaultInventoryCode: "GP",
    karatRequired: true,
    weightRequired: false,
    section2Title: "Piece & Gold Details",
    section2TitleAr: "تفاصيل القطعة والذهب",
    variants: [{ value: "gold-piece", label: "Gold By Piece", labelAr: "ذهب بالقطعة" }],
  },
  {
    type: "diamond",
    label: "Diamond",
    labelAr: "ألماس",
    defaultInventoryCode: "DD",
    karatRequired: false,
    weightRequired: false,
    section2Title: "Diamond Details",
    section2TitleAr: "تفاصيل الألماس",
    variants: [
      { value: "diamond-jewellery", label: "Diamond Jewellery", labelAr: "مجوهرات ألماس" },
      { value: "diamond-loose", label: "Diamond Loose Stone", labelAr: "ألماس حجر سائب", loose: true },
    ],
  },
  {
    type: "gemstone",
    label: "Gem Stone",
    labelAr: "حجر كريم",
    defaultInventoryCode: "GS",
    karatRequired: false,
    weightRequired: false,
    section2Title: "Gem Stone Details",
    section2TitleAr: "تفاصيل الحجر الكريم",
    variants: [
      { value: "gemstone-jewellery", label: "Gem Stone Jewellery", labelAr: "مجوهرات حجر كريم" },
      { value: "gemstone-loose", label: "Gem Stone Loose Stone", labelAr: "حجر كريم سائب", loose: true },
    ],
  },
  {
    type: "pearl",
    label: "Pearl",
    labelAr: "لؤلؤ",
    defaultInventoryCode: "PL",
    karatRequired: false,
    weightRequired: false,
    section2Title: "Pearl Details",
    section2TitleAr: "تفاصيل اللؤلؤ",
    variants: [
      { value: "pearl-jewellery", label: "Pearl Jewellery", labelAr: "مجوهرات لؤلؤ" },
      { value: "pearl-loose", label: "Loose Pearl", labelAr: "لؤلؤ سائب", loose: true },
    ],
  },
  {
    type: "watch",
    label: "Watch",
    labelAr: "ساعة",
    defaultInventoryCode: "WT",
    karatRequired: false,
    weightRequired: false,
    section2Title: "Watch Details",
    section2TitleAr: "تفاصيل الساعة",
    variants: [
      { value: "watch", label: "Watch (provisional)", labelAr: "ساعة (مبدئي)" },
    ],
  },
];

export function getTypeConfig(type: AssetType): InventoryTypeConfig {
  return INVENTORY_TYPE_CONFIGS.find((config) => config.type === type) ?? INVENTORY_TYPE_CONFIGS[0];
}

export function isLooseVariant(config: InventoryTypeConfig, variantValue: string): boolean {
  return Boolean(config.variants.find((variant) => variant.value === variantValue)?.loose);
}
