"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { CheckCircle2, Plus, Trash2 } from "lucide-react";
import { useLocale } from "next-intl";
import { useSearchParams } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { ErrorState } from "@/components/ui/error-state";
import { LoadingState } from "@/components/ui/loading-state";
import { PageHeader } from "@/components/ui/page-header";
import { useBranchContext } from "@/contexts/branch-context";
import { apiClient, canonicalBusinessHash, generateUUID, preConfirmAuthFreshness, requestContextSnapshot } from "@/lib/api/client";
import { isLocalReplayEnvironment, runPearlReplayFromSavedRequest, type PearlReplayMode, type PearlReplayResult } from "@/lib/debug/pearl-replay-helper";
import { buildSharedTaxRequest, SharedReceiveSection, type SharedReceiveState } from "@/components/inventory/shared-receive-section";
import { createPearlConfirmDiagnosticCorrelation, isPearlConfirmDiagnosticActive, isPearlConfirmInterceptionActive, recordPearlConfirmDiagnostic } from "@/lib/debug/pearl-confirm-dispatch";

type RecordValue = Record<string, any>;
type PearlGroup = RecordValue & { id: string };
const initialReceive: SharedReceiveState = { supplierId: "", locationId: "", purchaseDate: new Date().toISOString().slice(0, 10), taxTreatment: "", notes: "", rcmEvidence: {} };
const initialGroup = (id: string): PearlGroup => ({ id, quantity: "1", totalPearlWeight: "", pearlSizeId: "", pearlType: "", pearlColor: "", overtone: "", orient: "", pearlShape: "", luster: "", surfaceQuality: "", nacreQuality: "", pearlOrigin: "", pearlCost: "", currentValue: "", notes: "" });
const numberValue = (value: unknown) => Number(value || 0);
const money = (value: unknown, locale: string) => value == null ? "—" : new Intl.NumberFormat(locale === "ar" ? "ar-AE" : "en-AE", { style: "currency", currency: "AED", maximumFractionDigits: 8 }).format(Number(value));

function Field({ label, value, onChange, type = "text", required = false, readOnly = false }: { label: string; value: any; onChange?: (value: string) => void; type?: string; required?: boolean; readOnly?: boolean }) {
  return <label className="space-y-1"><span className="block text-[11px] font-bold text-slate-500">{label}{required ? " *" : ""}</span><input className={`input-base w-full ${readOnly ? "bg-slate-100 dark:bg-navy-950" : ""}`} dir={type === "number" ? "ltr" : undefined} type={type} step="any" value={value ?? ""} required={required} readOnly={readOnly} onChange={(event) => onChange?.(event.target.value)} /></label>;
}
type SelectOption = string | { value: string; label: string };
function SelectField({ label, value, onChange, options, required = false }: { label: string; value: any; onChange: (value: string) => void; options: SelectOption[]; required?: boolean }) {
  return <label className="space-y-1"><span className="block text-[11px] font-bold text-slate-500">{label}{required ? " *" : ""}</span><select className="input-base w-full" value={value ?? ""} required={required} onChange={(event) => onChange(event.target.value)}><option value="">—</option>{options.map((option) => { const optionValue = typeof option === "string" ? option : option.value; const optionLabel = typeof option === "string" ? option : option.label; return <option key={optionValue} value={optionValue}>{optionLabel}</option>; })}</select></label>;
}
function Section({ number, title, children }: { number: number; title: string; children: React.ReactNode }) { return <Card className="space-y-4 p-5"><h2 className="flex items-center gap-2 text-sm font-black"><span className="grid h-7 w-7 place-items-center rounded-full bg-brand-600 text-[11px] text-white">{number}</span>{title}</h2>{children}</Card>; }

export default function PearlJewelleryPage() {
  const locale = useLocale(); const rtl = locale === "ar"; const searchParams = useSearchParams(); const supplierHint = searchParams.get("supplierId") || ""; const { branchId, isReady } = useBranchContext();
  const [contract, setContract] = useState<RecordValue | null>(null); const [receive, setReceive] = useState(initialReceive); const [draft, setDraft] = useState<RecordValue>({ description: "", itemCode: "", karat: "18", goldColor: "", brand: "", model: "", modelNumber: "", grossWeight: "", purchaseGoldPrice: "", makingPerGram: "", currentMakingPerGram: "", sellingPrice: "", markupPercent: "", maximumDiscountPercent: "", rfid: "" });
  const [groups, setGroups] = useState<PearlGroup[]>([initialGroup("1")]); const [preview, setPreview] = useState<RecordValue | null>(null); const [sharedPreview, setSharedPreview] = useState<RecordValue | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [confirmation, setConfirmation] = useState(false); const [preparedReceive, setPreparedReceive] = useState<RecordValue | null>(null); const [result, setResult] = useState<any>(null); const [rcmVerified, setRcmVerified] = useState(false); const [confirmState, setConfirmState] = useState<"READY" | "CHECKING_SESSION" | "REVIEW_REQUIRED" | "BLOCKED_AUTH" | "READY_TO_CONFIRM">("READY");
  const [replayTestMode, setReplayTestMode] = useState(false); const [replayPayloadText, setReplayPayloadText] = useState(""); const [replayBusy, setReplayBusy] = useState(false); const [replayResult, setReplayResult] = useState<PearlReplayResult | null>(null); const [replayError, setReplayError] = useState(""); const [exactReplayDone, setExactReplayDone] = useState(false); const [changedReplayDone, setChangedReplayDone] = useState(false);
  const preparedHashRef = useRef<string | null>(null); const preparedContextRef = useRef<{ companyId?: string; branchId?: string } | null>(null); const diagnosticCorrelationRef = useRef<string | null>(null);
  const update = (key: string, value: any) => setDraft((current) => ({ ...current, [key]: value })); const updateReceive = (key: keyof SharedReceiveState, value: string) => setReceive((current) => ({ ...current, [key]: value })); const updateGroup = (id: string, key: string, value: any) => setGroups((current) => current.map((group) => group.id === id ? { ...group, [key]: value } : group));
  const masters = contract?.masters || []; const options = (category: string): string[] => Array.from(new Set<string>(masters.filter((row: RecordValue) => row.category === category && row.isActive !== false).map((row: RecordValue) => String(row.label)))); const pearlSizes = contract?.pearlSizes || [];
  const pearlSizeOptions: SelectOption[] = pearlSizes.map((row: RecordValue) => { const rawValue = String(row.value ?? row.displayValue ?? "").trim(); const compactValue = rawValue.includes(".") ? rawValue.replace(/0+$/, "").replace(/\.$/, "") : rawValue; return { value: String(row.id), label: `${compactValue} ${String(row.unit || "MM").toLowerCase()}`, numericValue: Number(row.value ?? row.displayValue) }; }).sort((left: RecordValue, right: RecordValue) => left.numericValue - right.numericValue).map(({ value, label }: { value: string; label: string }) => ({ value, label }));
  const selectedDescription = contract?.itemDescriptions?.find((entry: RecordValue) => entry.value === draft.description);
  const components = useMemo(() => groups.map(({ id, ...group }) => ({ ...group, componentKind: "PEARL", totalPearlWeight: group.totalPearlWeight, pearlSizeId: group.pearlSizeId || undefined })), [groups]);
  const item = useMemo(() => ({ profile: "PEARL_JEWELLERY", inventoryProfile: "PEARL_JEWELLERY", ...draft, itemCode: selectedDescription?.itemCode || draft.itemCode, components, taxTreatment: receive.taxTreatment, taxContext: receive.rcmEvidence }), [components, draft, receive, selectedDescription]);
  const profileReady = Boolean(contract && draft.description && selectedDescription && draft.goldColor && numberValue(draft.grossWeight) > 0 && numberValue(draft.karat) > 0 && numberValue(draft.purchaseGoldPrice) > 0 && draft.makingPerGram !== "" && draft.currentMakingPerGram !== "" && numberValue(draft.sellingPrice) > 0 && receive.taxTreatment && receive.supplierId && receive.locationId && groups.length && groups.every((group) => numberValue(group.totalPearlWeight) > 0 && numberValue(group.quantity) > 0));
  const receiveBody = useMemo(() => { const base = Number(preview?.historicalPurchase?.purchaseBasePreTax || 0); const piece = { ...item, type: "pearl", category: "Pearl Jewellery", purchaseCost: base, unitCost: base, price: Number(draft.sellingPrice), sellingPrice: Number(draft.sellingPrice), locationId: receive.locationId, supplierId: receive.supplierId, branchId, purchaseDate: receive.purchaseDate }; return { ...buildSharedTaxRequest(receive, contract?.taxPolicy), inventoryV2: true, supplierId: receive.supplierId, branchId, purchaseDate: receive.purchaseDate, items: [{ name: draft.description, description: draft.description, quantity: 1, unitCost: base, price: Number(draft.sellingPrice), grossWeight: numberValue(draft.grossWeight), inventoryV2: true, perPiece: [piece] }] }; }, [branchId, contract, draft, item, preview, receive]);
  useEffect(() => { if (!isReady) return; void (async () => { try { const response = await apiClient<any>("/inventory-v2/pearl-jewellery/contract", { locale, branchId: branchId || undefined }); const next = response?.data || response; setContract(next); if (supplierHint && next.suppliers?.some((row: RecordValue) => row.id === supplierHint)) setReceive((current) => ({ ...current, supplierId: supplierHint })); } catch (caught: any) { setError(caught?.message || "Contract unavailable"); } finally { setLoading(false); } })(); }, [branchId, isReady, locale, supplierHint]);
  useEffect(() => { if (!isPearlConfirmDiagnosticActive() || typeof window === "undefined") return; const correlationId = createPearlConfirmDiagnosticCorrelation(); recordPearlConfirmDiagnostic({ correlationId, eventName: "PEARL_CONFIRM_DIAGNOSTIC_READY", runtimeMode: process.env.NODE_ENV === "production" ? "NEXT_PRODUCTION_START_LOCALHOST" : "NEXT_NON_PRODUCTION", hostname: window.location.hostname, diagnosticsEnabled: true, interceptionEnabled: isPearlConfirmInterceptionActive() }); }, []);
  useEffect(() => { setReplayTestMode(isLocalReplayEnvironment()); }, []);
  useEffect(() => { if (!profileReady) { setPreview(null); setSharedPreview(null); return; } const timer = window.setTimeout(() => void (async () => { try { setError(""); const response = await apiClient<any>("/inventory-v2/pearl-jewellery/preview", { method: "POST", locale, branchId: branchId || undefined, body: JSON.stringify({ item }) }); setPreview(response?.data || response); } catch (caught: any) { setPreview(null); setError(caught?.message || "Profile preview unavailable"); } })(), 250); return () => window.clearTimeout(timer); }, [branchId, item, locale, profileReady]);
  useEffect(() => { if (!preview || !receive.supplierId || !receive.locationId || !receive.taxTreatment) { setSharedPreview(null); return; } const timer = window.setTimeout(() => void (async () => { try { const response = await apiClient<any>("/inventory-v2/receive-preview", { method: "POST", locale, branchId: branchId || undefined, body: JSON.stringify(receiveBody) }); setSharedPreview(response?.data || response); } catch (caught: any) { setSharedPreview(null); setError(caught?.message || "Shared receive preview unavailable"); } })(), 250); return () => window.clearTimeout(timer); }, [branchId, locale, preview, receiveBody]);
  const taxSummary = sharedPreview || preview?.historicalPurchase; const canReceive = Boolean(profileReady && preview?.sale && !preview.sale.approvalRequired && sharedPreview && receive.supplierId && receive.locationId && receive.taxTreatment && (!receive.taxTreatment.includes("REVERSE") || rcmVerified));
  const cloneRequest = <T,>(value: T): T => JSON.parse(JSON.stringify(value)) as T;
  const runConfirmPreflight = async (exactRequest: RecordValue, correlationId?: string): Promise<{ ok: boolean; authStatus: "FRESH" | "REFRESHED" | "BLOCKED_AUTH" }> => {
    const path = "/purchase-orders/receive"; const contextBefore = requestContextSnapshot(path, { branchId: branchId || undefined }); setConfirmState("CHECKING_SESSION");
    if (correlationId) recordPearlConfirmDiagnostic({ correlationId, eventName: "PEARL_CONFIRM_AUTH_PREFLIGHT_START", path });
    const auth = await preConfirmAuthFreshness(locale);
    if (correlationId) recordPearlConfirmDiagnostic({ correlationId, eventName: "PEARL_CONFIRM_AUTH_PREFLIGHT_RESULT", path, authStatus: auth.status, guardName: "authFreshness", guardResult: auth.status === "BLOCKED_AUTH" ? "FAIL" : "PASS", blockReason: auth.status === "BLOCKED_AUTH" ? "AUTH_BLOCKED" : undefined });
    if (auth.status === "BLOCKED_AUTH") { if (correlationId) recordPearlConfirmDiagnostic({ correlationId, eventName: "PEARL_CONFIRM_BLOCKED", path, blockReason: "AUTH_BLOCKED" }); setConfirmState("BLOCKED_AUTH"); setError(rtl ? "تعذر التحقق من الجلسة. لم يتم تنفيذ الاستلام." : "Session verification failed. Receive was not submitted."); return { ok: false, authStatus: auth.status }; }
    const contextAfter = requestContextSnapshot(path, { branchId: branchId || undefined });
    const preparedHash = await canonicalBusinessHash("purchase.receive", exactRequest); const currentCandidate = cloneRequest({ ...receiveBody, idempotencyKey: exactRequest.idempotencyKey }); const currentHash = await canonicalBusinessHash("purchase.receive", currentCandidate);
    const companyMatch = contextBefore.companyId === contextAfter.companyId; const branchMatch = contextBefore.branchId === contextAfter.branchId; const contextChanged = !companyMatch || !branchMatch;
    if (correlationId) recordPearlConfirmDiagnostic({ correlationId, eventName: "PEARL_CONFIRM_CONTEXT_RECOMPARE", path, contextMatch: !contextChanged, guardName: "companyBranchContext", guardResult: contextChanged ? "FAIL" : "PASS", blockReason: !companyMatch ? "COMPANY_CONTEXT_MISMATCH" : !branchMatch ? "BRANCH_CONTEXT_MISMATCH" : undefined });
    if (correlationId) recordPearlConfirmDiagnostic({ correlationId, eventName: "PEARL_CONFIRM_HASH_RECOMPARE", path, hashMatch: preparedHash === currentHash, guardName: "canonicalHash", guardResult: preparedHash === currentHash ? "PASS" : "FAIL", blockReason: preparedHash === currentHash ? undefined : "HASH_MISMATCH" });
    if (contextChanged || preparedHash !== currentHash) { if (correlationId) recordPearlConfirmDiagnostic({ correlationId, eventName: "PEARL_CONFIRM_BLOCKED", path, blockReason: !companyMatch ? "COMPANY_CONTEXT_MISMATCH" : !branchMatch ? "BRANCH_CONTEXT_MISMATCH" : "HASH_MISMATCH" }); preparedHashRef.current = null; preparedContextRef.current = null; setConfirmState("REVIEW_REQUIRED"); setError(rtl ? "تغيرت بيانات المراجعة. أعد فتح التأكيد للتحقق من الحالة الحالية." : "The review state changed. Reopen confirmation to verify the current state."); return { ok: false, authStatus: auth.status }; }
    preparedHashRef.current = preparedHash; preparedContextRef.current = contextAfter; setConfirmState("READY_TO_CONFIRM"); return { ok: true, authStatus: auth.status };
  };
  const openConfirmation = async () => { if (!canReceive || busy) return; const exact = cloneRequest({ ...receiveBody, idempotencyKey: generateUUID() }); setPreparedReceive(exact); setConfirmation(false); setError(""); if ((await runConfirmPreflight(exact)).ok) setConfirmation(true); };
  const submit = async () => {
    const correlationId = createPearlConfirmDiagnosticCorrelation(); diagnosticCorrelationRef.current = correlationId;
    recordPearlConfirmDiagnostic({ correlationId, eventName: "PEARL_CONFIRM_CLICK", method: "POST", path: "/purchase-orders/receive" });
    recordPearlConfirmDiagnostic({ correlationId, eventName: "PEARL_CONFIRM_HANDLER_ENTERED", method: "POST", path: "/purchase-orders/receive" });
    const canReceivePass = Boolean(canReceive); recordPearlConfirmDiagnostic({ correlationId, eventName: "PEARL_CONFIRM_GUARD_CAN_RECEIVE", guardName: "canReceive", guardResult: canReceivePass ? "PASS" : "FAIL", blockReason: canReceivePass ? undefined : "CAN_RECEIVE_FALSE" });
    const busyPass = !busy; recordPearlConfirmDiagnostic({ correlationId, eventName: "PEARL_CONFIRM_GUARD_BUSY", guardName: "busy", guardResult: busyPass ? "PASS" : "FAIL", blockReason: busyPass ? undefined : "BUSY_TRUE" });
    const exactRequest = preparedReceive; const preparedPass = Boolean(exactRequest?.idempotencyKey); recordPearlConfirmDiagnostic({ correlationId, eventName: "PEARL_CONFIRM_GUARD_PREPARED_REQUEST", guardName: "preparedRequest", guardResult: preparedPass ? "PASS" : "FAIL", preparedRequestPresent: preparedPass, blockReason: preparedPass ? undefined : "PREPARED_REQUEST_MISSING" });
    if (!canReceivePass || !busyPass || !preparedPass || !exactRequest) { recordPearlConfirmDiagnostic({ correlationId, eventName: "PEARL_CONFIRM_BLOCKED", blockReason: !canReceivePass ? "CAN_RECEIVE_FALSE" : !busyPass ? "BUSY_TRUE" : "PREPARED_REQUEST_MISSING" }); return; }
    setBusy(true); setError("");
    try {
      const preflight = await runConfirmPreflight(exactRequest, correlationId); if (!preflight.ok) return;
      if (preflight.authStatus === "REFRESHED") { recordPearlConfirmDiagnostic({ correlationId, eventName: "PEARL_CONFIRM_BLOCKED", blockReason: "AUTH_REFRESHED_REVIEW_REQUIRED", authStatus: preflight.authStatus }); setConfirmation(false); setError(rtl ? "تم تحديث الجلسة. راجع الطلب مرة أخرى قبل التأكيد." : "The session was refreshed. Review the request again before confirming."); return; }
      recordPearlConfirmDiagnostic({ correlationId, eventName: "PEARL_CONFIRM_READY_FOR_API", method: "POST", path: "/purchase-orders/receive", guardResult: "PASS", preparedRequestPresent: true });
      recordPearlConfirmDiagnostic({ correlationId, eventName: "PEARL_CONFIRM_API_CLIENT_ENTERED", method: "POST", path: "/purchase-orders/receive", apiClientEntered: true });
      const response = await apiClient<any>("/purchase-orders/receive", { method: "POST", locale, branchId: branchId || undefined, headers: { "Idempotency-Key": String(exactRequest.idempotencyKey) }, body: JSON.stringify(exactRequest), pearlConfirmDiagnostic: { correlationId } });
      recordPearlConfirmDiagnostic({ correlationId, eventName: "PEARL_CONFIRM_FETCH_RETURNED_OR_REJECTED", method: "POST", path: "/purchase-orders/receive", outcome: "RETURNED" }); setResult(response?.data || response); setConfirmation(false);
    } catch (caught: any) { recordPearlConfirmDiagnostic({ correlationId, eventName: "PEARL_CONFIRM_FETCH_RETURNED_OR_REJECTED", method: "POST", path: "/purchase-orders/receive", outcome: "REJECTED" }); setError(caught?.message || "Receive failed"); } finally { setBusy(false); }
  };
  const runTestReplay = async (mode: PearlReplayMode) => {
    if (replayBusy || (mode === "exact" && exactReplayDone) || (mode === "changed" && changedReplayDone)) return;
    setReplayBusy(true); setReplayError(""); setReplayResult(null);
    try {
      const saved = JSON.parse(replayPayloadText) as RecordValue;
      const request = mode === "changed" ? { ...saved, notes: `${String(saved.notes || "")} [controlled conflict proof]` } : saved;
      const next = await runPearlReplayFromSavedRequest({ request, mode, locale, branchId: branchId || undefined });
      setReplayResult(next); if (mode === "exact") setExactReplayDone(true); else setChangedReplayDone(true);
    } catch (caught: any) { setReplayError(caught?.message || "Replay proof failed"); } finally { setReplayBusy(false); }
  };
  if (loading) return <LoadingState variant="skeleton" />; if (error && !contract) return <ErrorState message={error} onRetry={() => window.location.reload()} />;
  return <div className="space-y-6"><PageHeader title={rtl ? "مجوهرات اللؤلؤ" : "Pearl Jewellery"} description={rtl ? "تسجيل قطعة مجوهرات لؤلؤية واحدة ببيانات معتمدة." : "Record one Pearl Jewellery piece with approved master data."} /><SharedReceiveSection state={receive} suppliers={contract?.suppliers || []} locations={contract?.locations || []} taxPolicy={contract?.taxPolicy} taxSummary={taxSummary} onChange={updateReceive} onRcmVerified={setRcmVerified} onRcmEvidenceChange={(evidence) => setReceive((current) => ({ ...current, rcmEvidence: evidence }))} rcmVerified={rcmVerified} />
    <Section number={1} title={rtl ? "تعريف القطعة" : "Item Identification"}><div className="grid gap-3 md:grid-cols-3"><SelectField label={rtl ? "وصف القطعة" : "Item Description"} value={draft.description} onChange={(value) => update("description", value)} options={(contract?.itemDescriptions || []).map((entry: RecordValue) => entry.value)} required /><Field label={rtl ? "العيار" : "Karat"} value={draft.karat} onChange={(value) => update("karat", value)} type="number" required /><SelectField label={rtl ? "لون الذهب" : "Gold Color"} value={draft.goldColor} onChange={(value) => update("goldColor", value)} options={options("GOLD_COLOR")} required /><Field label={rtl ? "العلامة" : "Brand"} value={draft.brand} onChange={(value) => update("brand", value)} /><Field label={rtl ? "الموديل" : "Model"} value={draft.model} onChange={(value) => update("model", value)} /><Field label={rtl ? "كود الصنف" : "Item Code"} value={selectedDescription?.itemCode || ""} readOnly /></div></Section>
    <Section number={2} title={rtl ? "معلومات الذهب" : "Gold Information"}><div className="grid gap-3 md:grid-cols-4"><Field label={rtl ? "الوزن الإجمالي (g)" : "Gross Weight (g)"} value={draft.grossWeight} onChange={(value) => update("grossWeight", value)} type="number" required /><Field label={rtl ? "وزن اللؤلؤ (g)" : "Pearl Weight (g)"} value={preview?.weights?.pearlWeight} readOnly /><Field label={rtl ? "وزن الأحجار الأخرى (g)" : "Other Stones Weight (g)"} value={preview?.weights?.otherStonesWeight} readOnly /><Field label={rtl ? "صافي الذهب (g)" : "Net Gold Weight (g)"} value={preview?.weights?.netGoldWeight} readOnly /></div><div className="grid gap-3 md:grid-cols-3"><Field label={rtl ? "الذهب الخالص 999.9" : "Pure Gold 999.9"} value={preview?.weights?.pureGoldWeight9999} readOnly /><Field label={rtl ? "الموقع" : "Location"} value={receive.locationId} readOnly /><Field label={rtl ? "الفرع" : "Branch"} value={branchId || "—"} readOnly /></div></Section>
    <Section number={3} title={rtl ? "معلومات اللؤلؤ" : "Pearl Information"}><div className="space-y-4">{groups.map((group, index) => <div key={group.id} className="rounded-2xl border border-border p-4"><div className="mb-3 flex items-center justify-between"><span className="font-black">{rtl ? `مجموعة لؤلؤ ${index + 1}` : `Pearl Group ${index + 1}`}</span>{groups.length > 1 && <Button variant="ghost" onClick={() => setGroups((current) => current.filter((entry) => entry.id !== group.id))}><Trash2 className="h-4 w-4" />{rtl ? "إزالة" : "Remove"}</Button>}</div><div className="grid gap-3 md:grid-cols-4"><Field label={rtl ? "الكمية" : "Quantity"} value={group.quantity} onChange={(value) => updateGroup(group.id, "quantity", value)} type="number" /><Field label={rtl ? "إجمالي وزن المجموعة (g)" : "Total Group Weight (g)"} value={group.totalPearlWeight} onChange={(value) => updateGroup(group.id, "totalPearlWeight", value)} type="number" required /><SelectField label={rtl ? "الحجم" : "Pearl Size"} value={group.pearlSizeId} onChange={(value) => updateGroup(group.id, "pearlSizeId", value)} options={pearlSizeOptions} /><SelectField label={rtl ? "النوع" : "Type"} value={group.pearlType} onChange={(value) => updateGroup(group.id, "pearlType", value)} options={options("PEARL_TYPE")} /><SelectField label={rtl ? "اللون" : "Color"} value={group.pearlColor} onChange={(value) => updateGroup(group.id, "pearlColor", value)} options={options("PEARL_COLOR")} /><SelectField label={rtl ? "اللمعة" : "Luster"} value={group.luster} onChange={(value) => updateGroup(group.id, "luster", value)} options={options("PEARL_LUSTER")} /><SelectField label={rtl ? "الشكل" : "Shape"} value={group.pearlShape} onChange={(value) => updateGroup(group.id, "pearlShape", value)} options={options("PEARL_SHAPE")} /><SelectField label={rtl ? "الأصل" : "Origin"} value={group.pearlOrigin} onChange={(value) => updateGroup(group.id, "pearlOrigin", value)} options={options("PEARL_ORIGIN")} /><Field label={rtl ? "تكلفة المجموعة" : "Group Pearl Cost"} value={group.pearlCost} onChange={(value) => updateGroup(group.id, "pearlCost", value)} type="number" /><Field label={rtl ? "القيمة الحالية" : "Current Value"} value={group.currentValue} onChange={(value) => updateGroup(group.id, "currentValue", value)} type="number" /><Field label={rtl ? "ملاحظات" : "Remarks"} value={group.notes} onChange={(value) => updateGroup(group.id, "notes", value)} /></div></div>)}<Button variant="secondary" onClick={() => setGroups((current) => [...current, initialGroup(String(Date.now()))])}><Plus className="h-4 w-4" />{rtl ? "إضافة مجموعة" : "Add Group"}</Button></div></Section>
    <Section number={4} title={rtl ? "معلومات الشراء" : "Purchase Information"}><div className="grid gap-3 md:grid-cols-4"><Field label={rtl ? "سعر الذهب عند الشراء / g" : "Purchase Gold Price / g"} value={draft.purchaseGoldPrice} onChange={(value) => update("purchaseGoldPrice", value)} type="number" required /><Field label={rtl ? "المصنعية / g" : "Making Charge / g"} value={draft.makingPerGram} onChange={(value) => update("makingPerGram", value)} type="number" required /><Field label={rtl ? "قيمة الذهب" : "Gold Purchase Value"} value={money(preview?.historicalPurchase?.goldValue, locale)} readOnly /><Field label={rtl ? "إجمالي الشراء" : "Purchase Total"} value={money(preview?.historicalPurchase?.totalPurchaseCost, locale)} readOnly /></div><div className="grid gap-3 md:grid-cols-3"><Field label={rtl ? "أساس الشراء قبل الضريبة" : "Purchase Base Before Tax"} value={money(preview?.historicalPurchase?.purchaseBasePreTax, locale)} readOnly /><Field label={rtl ? "الضريبة" : "Purchase VAT"} value={money(preview?.historicalPurchase?.vatAmount, locale)} readOnly /><Field label={rtl ? "ملخص الضريبة" : "Tax Summary"} value={taxSummary?.taxTreatment || receive.taxTreatment || "—"} readOnly /></div></Section>
    <Section number={5} title={rtl ? "معلومات التكلفة الحالية" : "Current Cost Information"}><div className="grid gap-3 md:grid-cols-4"><Field label={rtl ? "سعر الذهب الحالي" : "Current Gold Rate"} value={preview?.currentCost?.goldRate} readOnly /><Field label={rtl ? "المصنعية الحالية / g" : "Current Making / g"} value={draft.currentMakingPerGram} onChange={(value) => update("currentMakingPerGram", value)} type="number" required /><Field label={rtl ? "قيمة اللؤلؤ الحالية" : "Current Pearl Value"} value={money(preview?.currentCost?.pearlValue, locale)} readOnly /><Field label={rtl ? "إجمالي القيمة الحالية" : "Current Item Cost"} value={money(preview?.currentCost?.totalCurrentCost, locale)} readOnly /></div></Section>
    <Section number={6} title={rtl ? "معلومات البيع" : "Sales Information"}><div className="grid gap-3 md:grid-cols-4"><Field label={rtl ? "سعر البيع" : "Selling Price"} value={draft.sellingPrice} onChange={(value) => update("sellingPrice", value)} type="number" required /><Field label={rtl ? "نسبة الزيادة %" : "Markup %"} value={draft.markupPercent} onChange={(value) => update("markupPercent", value)} type="number" /><Field label={rtl ? "الخصم الأقصى %" : "Maximum Discount %"} value={draft.maximumDiscountPercent} onChange={(value) => update("maximumDiscountPercent", value)} type="number" /><Field label={rtl ? "الربح المتوقع" : "Expected Profit"} value={money(preview?.sale?.expectedProfit, locale)} readOnly /></div></Section>
    <Section number={7} title={rtl ? "معلومات الوسم" : "Tag Information"}><div className="grid gap-3 md:grid-cols-3"><Field label={rtl ? "الباركود" : "Barcode"} value={rtl ? "ينشأ بعد الاستلام" : "Generated after receive"} readOnly /><Field label="RFID" value={draft.rfid} onChange={(value) => update("rfid", value)} /><Field label={rtl ? "الحالة" : "Status"} value="AVAILABLE" readOnly /></div></Section>
    <Section number={8} title={rtl ? "معلومات الحالة" : "Item Status Information"}><div className="grid gap-3 md:grid-cols-3"><Field label={rtl ? "الحالة التشغيلية" : "Operational Status"} value="AVAILABLE" readOnly /><Field label={rtl ? "الحالة" : "Condition"} value="NEW" readOnly /><Field label={rtl ? "الموقع" : "Location"} value={receive.locationId} readOnly /></div></Section>
    <Section number={9} title={rtl ? "التدقيق والنظام" : "Audit & System Information"}><div className="grid gap-3 md:grid-cols-2"><Field label={rtl ? "المورد" : "Supplier"} value={receive.supplierId} readOnly /><Field label={rtl ? "تاريخ الشراء" : "Purchase Date"} value={receive.purchaseDate} readOnly /><Field label={rtl ? "ملاحظات" : "Notes"} value={receive.notes} onChange={(value) => updateReceive("notes", value)} /></div></Section>
    <Card className="space-y-3 p-4"><div className="flex flex-wrap gap-2"><Badge tone={profileReady ? "green" : "amber"}>{rtl ? `معاينة الملف: ${profileReady ? "جاهزة" : "غير جاهزة"}` : `Profile Preview: ${profileReady ? "READY" : "NOT READY"}`}</Badge><Badge tone={sharedPreview ? "green" : "amber"}>{rtl ? `المعاينة المشتركة: ${sharedPreview ? "جاهزة" : "غير جاهزة"}` : `Shared Receive Preview: ${sharedPreview ? "READY" : "NOT READY"}`}</Badge><Badge tone={confirmState === "READY_TO_CONFIRM" ? "green" : "amber"} data-testid="pearl-confirm-auth-state">{rtl ? `فحص الجلسة: ${confirmState === "READY_TO_CONFIRM" ? "جاهز للتأكيد" : confirmState === "CHECKING_SESSION" ? "جارٍ التحقق" : "بانتظار المراجعة"}` : `Session preflight: ${confirmState === "READY_TO_CONFIRM" ? "READY TO CONFIRM" : confirmState === "CHECKING_SESSION" ? "CHECKING" : "REVIEW REQUIRED"}`}</Badge></div>{error && <p className="text-sm text-rose-600">{error}</p>}{result && <p className="text-sm font-bold text-emerald-700"><CheckCircle2 className="me-1 inline h-4 w-4" />{rtl ? "تم الاستلام بنجاح" : "Receive completed"}</p>}<div className="flex justify-end"><Button onClick={() => void openConfirmation()} disabled={!canReceive || busy || confirmState === "CHECKING_SESSION"}>{rtl ? "مراجعة وتأكيد الاستلام" : "Review and Confirm Receive"}</Button></div></Card>
    {confirmation && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><Card className="w-full max-w-2xl space-y-5 p-6"><h2 className="text-base font-black">{rtl ? "تأكيد استلام مجوهرات اللؤلؤ" : "Confirm Pearl Jewellery Receive"}</h2><div className="grid gap-3 sm:grid-cols-2"><Field label={rtl ? "المورد" : "Supplier"} value={receive.supplierId} readOnly /><Field label={rtl ? "الموقع" : "Location"} value={receive.locationId} readOnly /><Field label={rtl ? "أساس الشراء" : "Purchase Base Before Tax"} value={money(preview?.historicalPurchase?.purchaseBasePreTax, locale)} readOnly /><Field label={rtl ? "الضريبة" : "VAT"} value={money(preview?.historicalPurchase?.vatAmount, locale)} readOnly /></div>{preparedReceive && <details data-testid="prepared-pearl-receive-payload" className="rounded border border-slate-200 p-3"><summary className="cursor-pointer text-sm font-bold">{rtl ? "الطلب المحفوظ للمراجعة" : "Prepared request details"}</summary><pre className="mt-3 max-h-72 overflow-auto whitespace-pre-wrap text-xs">{JSON.stringify(preparedReceive, null, 2)}</pre></details>}<div className="flex justify-end gap-3"><Button variant="secondary" onClick={() => setConfirmation(false)} disabled={busy}>{rtl ? "إلغاء" : "Cancel"}</Button><Button onClick={() => void submit()} disabled={busy || !preparedReceive}>{rtl ? "تأكيد الاستلام" : "Confirm Receive"}</Button></div></Card></div>}
    {replayTestMode && <Card data-testid="pearl-local-replay-harness" className="space-y-3 border-amber-400 p-4"><h2 className="text-sm font-black">Local acceptance replay harness</h2><p className="text-xs text-slate-500">Test-only localhost channel. Uses the existing authenticated API client and never creates a new receive.</p><textarea data-testid="pearl-replay-payload" className="input-base min-h-32 w-full font-mono text-xs" value={replayPayloadText} onChange={(event) => setReplayPayloadText(event.target.value)} placeholder="Paste the saved exact request JSON" /><div className="flex flex-wrap gap-2"><Button data-testid="pearl-replay-exact" onClick={() => void runTestReplay("exact")} disabled={replayBusy || exactReplayDone || !replayPayloadText}>Replay exact saved request</Button><Button variant="secondary" data-testid="pearl-replay-changed" onClick={() => void runTestReplay("changed")} disabled={replayBusy || changedReplayDone || !replayPayloadText || !exactReplayDone}>Send same-key changed-payload conflict</Button></div>{replayError && <p className="text-sm text-rose-600">{replayError}</p>}{replayResult && <pre data-testid="pearl-replay-result" className="whitespace-pre-wrap text-xs">{JSON.stringify(replayResult, null, 2)}</pre>}</Card>}
  </div>;
}
